import { getSheetData, parseDate } from "@/lib/sheets";
import { NextResponse } from "next/server";
function findCol(headers, ...candidates) {
  for (const c of candidates) {
    const idx = headers.findIndex((h) => h?.toLowerCase().includes(c.toLowerCase()));
    if (idx !== -1) return idx;
  }
  return -1;
}
export async function GET(req) {
  try {
    const { searchParams } = new URL(req.url);
    const month = parseInt(searchParams.get("month") || new Date().getMonth() + 1);
    const year = parseInt(searchParams.get("year") || new Date().getFullYear());
    const rows = await getSheetData("Input Metrics!A:Z");
    if (!rows || rows.length < 2) return NextResponse.json({ data: {} });
    const headers = rows[0].map((h) => h?.trim() || "");
    const cols = {
      createdAt: findCol(headers, "Created at"),
      createdBy: findCol(headers, "Created by"),
      leadGenAt: findCol(headers, "Lead Generated at"),
      leadGenBy: findCol(headers, "Lead Generated by"),
      primarySource: findCol(headers, "Primary Source", "Lead Source", "Source"),
      completedDate: findCol(headers, "Completed Date", "Completed at"),
      meetingOwner: findCol(headers, "Meeting Owner"),
      meetingStatus: findCol(headers, "Status", "Meeting Status"),
      callOwner: findCol(headers, "Call Owner"),
    };
    const dataRows = rows.slice(1);
    function inMonth(dateStr) {
      const d = parseDate(dateStr);
      if (!d) return false;
      return d.getMonth() + 1 === month && d.getFullYear() === year;
    }
    function getDay(dateStr) {
      const d = parseDate(dateStr);
      return d ? d.getDate() : null;
    }
    const metrics = { leadActivation: {}, leadGeneration: {}, meetingsConducted: {}, callsMade: {} };
    function increment(metric, poc, day) {
      if (!poc || !day) return;
      if (!metrics[metric][poc]) metrics[metric][poc] = {};
      metrics[metric][poc][day] = (metrics[metric][poc][day] || 0) + 1;
    }
    for (const row of dataRows) {
      const get = (idx) => (idx !== -1 ? row[idx]?.trim() : "");
      if (cols.createdAt !== -1 && cols.createdBy !== -1) {
        const date = get(cols.createdAt); const poc = get(cols.createdBy);
        if (date && poc && inMonth(date)) increment("leadActivation", poc, getDay(date));
      }
      if (cols.leadGenAt !== -1 && cols.leadGenBy !== -1) {
        const date = get(cols.leadGenAt); const poc = get(cols.leadGenBy);
        const source = get(cols.primarySource).toLowerCase();
        if (date && poc && inMonth(date) && source !== "inbound") increment("leadGeneration", poc, getDay(date));
      }
      if (cols.completedDate !== -1 && cols.meetingOwner !== -1) {
        const date = get(cols.completedDate); const poc = get(cols.meetingOwner);
        const status = get(cols.meetingStatus).toLowerCase();
        if (date && poc && inMonth(date) && status === "completed") increment("meetingsConducted", poc, getDay(date));
      }
      if (cols.callOwner !== -1) {
        const date = get(cols.createdAt); const poc = get(cols.callOwner);
        if (date && poc && inMonth(date)) increment("callsMade", poc, getDay(date));
      }
    }
    return NextResponse.json({ data: metrics, month, year });
  } catch (err) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
